### ISSUE TITLE
DepoolingLayer

### ISSUE THREAD

**Issue by sankar19** [YutingZhang/caffe-recon-dec#2]
Hi,

Using "DepoolingLayer" will I be able to implement the SegNet (Encoder-Decoder architecture): https://arxiv.org/abs/1511.00561?

Segnet code seems to be built on old Caffe.

Thanks.

**Comment by YutingZhang** [comment]
@sankar19 Yes. You can use the DepoolingLayer to implement SegNet.

You can also take a look at the following paper (published in ICCV 2015):
https://arxiv.org/abs/1505.04366
They have code released (http://cvlab.postech.ac.kr/research/decouplednet/)

Compared to their unpooling implementation, my DepoolingLayer is more general (e.g., support overlapping pooling patch).

**Comment by sankar19** [comment]
Hi, Thanks. I was able to use your caffe code for SegNet last week.

**Comment by YutingZhang** [comment]
@sankar19  Cool. Glad to know that.

**Comment by sankar19** [comment]
@YutingZhang   

I1208 12:06:39.877930   668 layer_factory.hpp:77] Creating layer pool1
I1208 12:06:39.877935   668 layer_factory.cpp:90] cuDNN does not support multiple tops. Using Caffe's own pooling layer.
I1208 12:06:39.877948   668 net.cpp:425] pool1 <- conv1_2
I1208 12:06:39.877954   668 net.cpp:399] pool1 -> pool1
I1208 12:06:39.877962   668 net.cpp:399] pool1 -> pool1_mask

Do you get this message when you run your code? I use cuda 8.0 with cudnn 5.1. I am not sure if this is a issue. I need to check the pool mask output, to check if it works Ok.

Thanks,
Sankar

**Comment by sankar19** [comment]
I guess for that layer       
return shared_ptr<Layer<Dtype> >(new PoolingLayer<Dtype>(param));
is used instead of CuDNNPoolingLayer which should be fine. Thanks.

**Comment by YutingZhang** [comment]
@sankar19 You can ignore that warning. There will be no problem.

Only the basic pooling layer has CUDNN implementation. When CUDNN implementation is not available it automatically switch to ordinary CUDA implementation (and output that warning.)
