### ISSUE TITLE
hello, I have a problem on rebuild your caffe project

### ISSUE THREAD

**Issue by Alien9427** [YutingZhang/caffe-recon-dec#3]
When rebuilding the caffe project, the make all, make test and make runtest goes well. But when I use the new layers you added in the project, I get the error on "Unknown layer type: Depooling". And I find that the new layers, such as DepoolingLayer, SafeInvLayer are not contained in. I checked the caffe.proto and found that the new layers were not added in enum LayerType {}. I wonder if the caffe.proto needs to be revised by ourselves or there is something wrong with my operations of rebuilding caffe project.
Thank you.

**Comment by YutingZhang** [comment]
@Alien9427 I think you used an obsolete format of the caffe prototxt defined in V1LayerParameter.

You can take a look at any prototxt file in this repository, e.g., https://github.com/YutingZhang/caffe-recon-dec/blob/master/recon-dec/vggnet/baseline/cls_only_deploy.prototxt

Then you should be able to figure out how the current version of caffe prototxt looks like.

Thanks
